CREATE TABLE EMPLOYEE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  AGE INT NOT NULL,
  MOBILE_NUMBER VARCHAR(20) NOT NULL UNIQUE,  
  BEFORE_VALUE DECIMAL(10,2),  
  AFTER_VALUE DECIMAL(10,2)
);


